[
"Id,Surname,Christian,email,phone,ebu number,don't send email,not active",
[1,"Davies","Jo ","","","",""],
[2,"Woodhouse","Pam","","","",""],
[3,"thomas","Ken","","","",""],
[4,"Loyn","Betty","","","",""],
[5,"Hathaway","Margaret","","","",""],
[6,"Roe","Pat","","","",""],
[7,"Richards","Alun","","","",""],
[8,"James","Margaret","","","",""],
[9,"Brookes","Betty","","","",""],
[10,"Thomas","Elenid","","","",""],
[11,"Harrison","Jean","","","",""],
[12,"Jenkins","Mair","","","",""],
[13,"Blair","Joyce","","","",""],
[14,"Ellis","Margaret","","","",""],
[15,"Hayes","Dai","","","",""],
[16,"Valentine","John","","","",""],
[17,"Jones","Mike","","","",""],
[18,"Bellamy","Keith","","","",""],
[19,"Rowley","Herbie","","","",""],
[20,"Anthony","Doreen","","","",""],
[21,"Boyle","Roger","","","",""],
[22,"thomas","Jeff","","","",""]
]
